spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Student
    username: root
    password: carm2394
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
---
environment: test
spring:
  datasource:
  url: jdbc:h2:mem:test
  username: test
  password: test
  driver-class-name: org.h2.Driver
h2:
  console:
  enabled: true